version: '3.4'

services:
  orderdb:
    image: mcr.microsoft.com/mssql/server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
